# Camera Forward
- ros_topic_name: "/stinger/camera_0/image_raw"
  gz_topic_name: "/stinger/camera_0/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/stinger/scan"
  gz_topic_name: "/stinger/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS